// <auto-generated />
using System;
using DistSysAcwServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DistSysAcwServer.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20250415145049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DistSysAcwServer.Models.Log", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LogDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserApiKey")
                        .HasColumnType("TEXT");

                    b.HasKey("LogID");

                    b.HasIndex("UserApiKey");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DistSysAcwServer.Models.LogArchive", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LogDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LogID");

                    b.ToTable("LogArchives");
                });

            modelBuilder.Entity("DistSysAcwServer.Models.User", b =>
                {
                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ApiKey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DistSysAcwServer.Models.Log", b =>
                {
                    b.HasOne("DistSysAcwServer.Models.User", null)
                        .WithMany("Logs")
                        .HasForeignKey("UserApiKey");
                });

            modelBuilder.Entity("DistSysAcwServer.Models.User", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
